name: BrewedPOTS

channels:
    - conda-forge
    - pytorch
    - pyg
    - nodefaults

dependencies:
    - conda-forge::pypots
    - conda-forge::jupyterlab

    # optional
    - pyg::pyg
    - pyg::pytorch-scatter
    - pyg::pytorch-sparse
